### ISSUE TITLE
Issues Running app on web 

### ISSUE THREAD

**Issue by Lakhankumawat** [gdscnitp/Delrit#10]
## Is it configured yet to run on web ?
```
Error: MissingPluginException(No implementation found for method loadEnvVariables on channel flutter_config)
    at Object.throw_ [as throw] (http://localhost:49565/dart_sdk.js:5061:11)
    at MethodChannel._invokeMethod (http://localhost:49565/packages/flutter/src/services/restoration.dart.lib.js:1526:21)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:49565/dart_sdk.js:38640:33
    at _RootZone.runUnary (http://localhost:49565/dart_sdk.js:38511:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:49565/dart_sdk.js:33713:29)
    at handleValueCallback (http://localhost:49565/dart_sdk.js:34265:49)
    at Function._propagateToListeners (http://localhost:49565/dart_sdk.js:34303:17)
    at _Future.new.[_completeWithValue] (http://localhost:49565/dart_sdk.js:34151:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:49565/dart_sdk.js:34172:35)
    at Object._microtaskLoop (http://localhost:49565/dart_sdk.js:38778:13)
    at _startMicrotaskLoop (http://localhost:49565/dart_sdk.js:38784:13)
    at http://localhost:49565/dart_sdk.js:34519:9

```

**Comment by ViAsmit** [comment]
@Lakhankumawat Some Plugins related to Google Maps that we are using are not yet supported for web platform, So, We can either wait, or we can move to some other method if it doesn't get supported till our showcase.
Currently, our main focus is to complete the basic application, then we can always work on these issues.

**Comment by Lakhankumawat** [comment]
Ok great, i thought there are web unix folders so i thought you guys might be working along way , let's keep it later then .
